[default]
timeout = 180

[musicbank]
title = "뮤직뱅크"
url = "https://program.naver.com/p/659774/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"

[showmusiccore]
title = "쇼! 음악중심"
url = "https://program.naver.com/p/658837/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"

[inkigayo]
title = "인기가요"
url = "https://program.naver.com/p/658960/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"

[mcountdown]
title = "엠카운트다운"
url = "https://program.naver.com/p/659252/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"

[theshow]
title = "더쇼"
url = "https://program.naver.com/p/3235720/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"

[showchampion]
title = "쇼챔피언"
url = "https://program.naver.com/p/669613/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"

[satfreedom]
title = "불후의 명곡"
url = "https://program.naver.com/p/670142/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"

[mask]
title = "복면가왕"
url = "https://program.naver.com/p/2404757/clip"
entrySelector = "ul.ClipCardList_wrap__2K642 li.ClipCard_item__1ly4h"
titleSelector = "strong.ClipCard_title__2I1pd"
linkSelector = "a.ClipCard_link__2XpqM"
contentSelector = "span.ClipCard_time__128vc"
waitForSelector = "li.ClipCard_item__1ly4h"
onFail = "stale"
